/* 
* @Author: kuychaco
* @Date:   2015-05-26 21:47:36
* @Last Modified by:   kuychaco
* @Last Modified time: 2015-05-26 21:51:01
*/

'use strict';

var issues = [
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/issues/8",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/8/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/8/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/8/events",
  "html_url": "https://github.com/relentlessbreakfast/test/issues/8",
  "id": 81183631,
  "number": 8,
  "title": "learn bookshelf",
  "user": {
    "login": "kuychaco",
    "id": 7910250,
    "avatar_url": "https://avatars.githubusercontent.com/u/7910250?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kuychaco",
    "html_url": "https://github.com/kuychaco",
    "followers_url": "https://api.github.com/users/kuychaco/followers",
    "following_url": "https://api.github.com/users/kuychaco/following{/other_user}",
    "gists_url": "https://api.github.com/users/kuychaco/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kuychaco/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kuychaco/subscriptions",
    "organizations_url": "https://api.github.com/users/kuychaco/orgs",
    "repos_url": "https://api.github.com/users/kuychaco/repos",
    "events_url": "https://api.github.com/users/kuychaco/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kuychaco/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "url": "https://api.github.com/repos/relentlessbreakfast/test/labels/create%20database",
      "name": "create database",
      "color": "bfd4f2"
    },
    {
      "url": "https://api.github.com/repos/relentlessbreakfast/test/labels/create%20database%20-%20define%20schema",
      "name": "create database - define schema",
      "color": "0052cc"
    }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2015-05-26T23:29:02Z",
  "updated_at": "2015-05-26T23:42:01Z",
  "closed_at": null,
  "body": ""
  },
  // ------------------------------------------------------------------------------------------------
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/issues/7",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/7/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/7/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/7/events",
  "html_url": "https://github.com/relentlessbreakfast/test/issues/7",
  "id": 81181697,
  "number": 7,
  "title": "write db-config",
  "user": {
  "login": "kuychaco",
  "id": 7910250,
  "avatar_url": "https://avatars.githubusercontent.com/u/7910250?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kuychaco",
  "html_url": "https://github.com/kuychaco",
  "followers_url": "https://api.github.com/users/kuychaco/followers",
  "following_url": "https://api.github.com/users/kuychaco/following{/other_user}",
  "gists_url": "https://api.github.com/users/kuychaco/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kuychaco/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kuychaco/subscriptions",
  "organizations_url": "https://api.github.com/users/kuychaco/orgs",
  "repos_url": "https://api.github.com/users/kuychaco/repos",
  "events_url": "https://api.github.com/users/kuychaco/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kuychaco/received_events",
  "type": "User",
  "site_admin": false
  },
  "labels": [
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/labels/create%20database",
  "name": "create database",
  "color": "bfd4f2"
  },
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/labels/in%20progress",
  "name": "in progress",
  "color": "ededed"
  }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2015-05-26T23:22:13Z",
  "updated_at": "2015-05-26T23:33:15Z",
  "closed_at": null,
  "body": ""
  },
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/issues/6",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/6/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/6/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/6/events",
  "html_url": "https://github.com/relentlessbreakfast/test/issues/6",
  "id": 81180654,
  "number": 6,
  "title": "learn sequelize",
  "user": {
  "login": "kuychaco",
  "id": 7910250,
  "avatar_url": "https://avatars.githubusercontent.com/u/7910250?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kuychaco",
  "html_url": "https://github.com/kuychaco",
  "followers_url": "https://api.github.com/users/kuychaco/followers",
  "following_url": "https://api.github.com/users/kuychaco/following{/other_user}",
  "gists_url": "https://api.github.com/users/kuychaco/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kuychaco/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kuychaco/subscriptions",
  "organizations_url": "https://api.github.com/users/kuychaco/orgs",
  "repos_url": "https://api.github.com/users/kuychaco/repos",
  "events_url": "https://api.github.com/users/kuychaco/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kuychaco/received_events",
  "type": "User",
  "site_admin": false
  },
  "labels": [
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/labels/create%20database",
  "name": "create database",
  "color": "bfd4f2"
  },
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/labels/create%20database%20-%20define%20schema",
  "name": "create database - define schema",
  "color": "0052cc"
  }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2015-05-26T23:19:03Z",
  "updated_at": "2015-05-26T23:42:05Z",
  "closed_at": null,
  "body": ""
  },
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/issues/5",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/5/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/5/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/5/events",
  "html_url": "https://github.com/relentlessbreakfast/test/issues/5",
  "id": 81179852,
  "number": 5,
  "title": "define schema",
  "user": {
  "login": "kuychaco",
  "id": 7910250,
  "avatar_url": "https://avatars.githubusercontent.com/u/7910250?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kuychaco",
  "html_url": "https://github.com/kuychaco",
  "followers_url": "https://api.github.com/users/kuychaco/followers",
  "following_url": "https://api.github.com/users/kuychaco/following{/other_user}",
  "gists_url": "https://api.github.com/users/kuychaco/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kuychaco/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kuychaco/subscriptions",
  "organizations_url": "https://api.github.com/users/kuychaco/orgs",
  "repos_url": "https://api.github.com/users/kuychaco/repos",
  "events_url": "https://api.github.com/users/kuychaco/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kuychaco/received_events",
  "type": "User",
  "site_admin": false
  },
  "labels": [
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/labels/cluster",
  "name": "cluster",
  "color": "009800"
  },
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/labels/create%20database",
  "name": "create database",
  "color": "bfd4f2"
  },
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/labels/in%20progress",
  "name": "in progress",
  "color": "ededed"
  }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2015-05-26T23:17:14Z",
  "updated_at": "2015-05-26T23:33:18Z",
  "closed_at": null,
  "body": ""
  },
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/issues/4",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/4/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/4/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/4/events",
  "html_url": "https://github.com/relentlessbreakfast/test/issues/4",
  "id": 81179485,
  "number": 4,
  "title": "create database",
  "user": {
  "login": "kuychaco",
  "id": 7910250,
  "avatar_url": "https://avatars.githubusercontent.com/u/7910250?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kuychaco",
  "html_url": "https://github.com/kuychaco",
  "followers_url": "https://api.github.com/users/kuychaco/followers",
  "following_url": "https://api.github.com/users/kuychaco/following{/other_user}",
  "gists_url": "https://api.github.com/users/kuychaco/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kuychaco/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kuychaco/subscriptions",
  "organizations_url": "https://api.github.com/users/kuychaco/orgs",
  "repos_url": "https://api.github.com/users/kuychaco/repos",
  "events_url": "https://api.github.com/users/kuychaco/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kuychaco/received_events",
  "type": "User",
  "site_admin": false
  },
  "labels": [
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/labels/cluster",
  "name": "cluster",
  "color": "009800"
  },
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/labels/ready",
  "name": "ready",
  "color": "ededed"
  }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 0,
  "created_at": "2015-05-26T23:16:17Z",
  "updated_at": "2015-05-26T23:33:07Z",
  "closed_at": null,
  "body": ""
  },
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/issues/3",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/3/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/3/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/3/events",
  "html_url": "https://github.com/relentlessbreakfast/test/issues/3",
  "id": 81161716,
  "number": 3,
  "title": "Use D3 to build the cluster",
  "user": {
  "login": "cwhwang1986",
  "id": 8173733,
  "avatar_url": "https://avatars.githubusercontent.com/u/8173733?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/cwhwang1986",
  "html_url": "https://github.com/cwhwang1986",
  "followers_url": "https://api.github.com/users/cwhwang1986/followers",
  "following_url": "https://api.github.com/users/cwhwang1986/following{/other_user}",
  "gists_url": "https://api.github.com/users/cwhwang1986/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/cwhwang1986/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/cwhwang1986/subscriptions",
  "organizations_url": "https://api.github.com/users/cwhwang1986/orgs",
  "repos_url": "https://api.github.com/users/cwhwang1986/repos",
  "events_url": "https://api.github.com/users/cwhwang1986/events{/privacy}",
  "received_events_url": "https://api.github.com/users/cwhwang1986/received_events",
  "type": "User",
  "site_admin": false
  },
  "labels": [ ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/milestones/2",
  "html_url": "https://github.com/relentlessbreakfast/test/milestones/Cluster%20Dragging%20feature",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/test/milestones/2/labels",
  "id": 1134853,
  "number": 2,
  "title": "Cluster Dragging feature",
  "description": "This cluster will implement the draggability of cluster on our UI ",
  "creator": {
  "login": "cwhwang1986",
  "id": 8173733,
  "avatar_url": "https://avatars.githubusercontent.com/u/8173733?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/cwhwang1986",
  "html_url": "https://github.com/cwhwang1986",
  "followers_url": "https://api.github.com/users/cwhwang1986/followers",
  "following_url": "https://api.github.com/users/cwhwang1986/following{/other_user}",
  "gists_url": "https://api.github.com/users/cwhwang1986/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/cwhwang1986/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/cwhwang1986/subscriptions",
  "organizations_url": "https://api.github.com/users/cwhwang1986/orgs",
  "repos_url": "https://api.github.com/users/cwhwang1986/repos",
  "events_url": "https://api.github.com/users/cwhwang1986/events{/privacy}",
  "received_events_url": "https://api.github.com/users/cwhwang1986/received_events",
  "type": "User",
  "site_admin": false
  },
  "open_issues": 1,
  "closed_issues": 0,
  "state": "open",
  "created_at": "2015-05-26T22:16:24Z",
  "updated_at": "2015-05-26T22:18:23Z",
  "due_on": null,
  "closed_at": null
  },
  "comments": 0,
  "created_at": "2015-05-26T22:18:02Z",
  "updated_at": "2015-05-26T22:18:23Z",
  "closed_at": null,
  "body": ""
  },
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/issues/2",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/2/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/2/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/2/events",
  "html_url": "https://github.com/relentlessbreakfast/test/issues/2",
  "id": 81161254,
  "number": 2,
  "title": "learn sequelize",
  "user": {
  "login": "kuychaco",
  "id": 7910250,
  "avatar_url": "https://avatars.githubusercontent.com/u/7910250?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kuychaco",
  "html_url": "https://github.com/kuychaco",
  "followers_url": "https://api.github.com/users/kuychaco/followers",
  "following_url": "https://api.github.com/users/kuychaco/following{/other_user}",
  "gists_url": "https://api.github.com/users/kuychaco/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kuychaco/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kuychaco/subscriptions",
  "organizations_url": "https://api.github.com/users/kuychaco/orgs",
  "repos_url": "https://api.github.com/users/kuychaco/repos",
  "events_url": "https://api.github.com/users/kuychaco/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kuychaco/received_events",
  "type": "User",
  "site_admin": false
  },
  "labels": [ ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/milestones/1",
  "html_url": "https://github.com/relentlessbreakfast/test/milestones/set%20up%20database",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/test/milestones/1/labels",
  "id": 1134851,
  "number": 1,
  "title": "set up database",
  "description": "",
  "creator": {
  "login": "kuychaco",
  "id": 7910250,
  "avatar_url": "https://avatars.githubusercontent.com/u/7910250?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kuychaco",
  "html_url": "https://github.com/kuychaco",
  "followers_url": "https://api.github.com/users/kuychaco/followers",
  "following_url": "https://api.github.com/users/kuychaco/following{/other_user}",
  "gists_url": "https://api.github.com/users/kuychaco/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kuychaco/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kuychaco/subscriptions",
  "organizations_url": "https://api.github.com/users/kuychaco/orgs",
  "repos_url": "https://api.github.com/users/kuychaco/repos",
  "events_url": "https://api.github.com/users/kuychaco/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kuychaco/received_events",
  "type": "User",
  "site_admin": false
  },
  "open_issues": 2,
  "closed_issues": 0,
  "state": "open",
  "created_at": "2015-05-26T22:15:38Z",
  "updated_at": "2015-05-26T22:17:25Z",
  "due_on": null,
  "closed_at": null
  },
  "comments": 0,
  "created_at": "2015-05-26T22:16:26Z",
  "updated_at": "2015-05-26T22:17:25Z",
  "closed_at": null,
  "body": ""
  },
  {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/issues/1",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/1/labels{/name}",
  "comments_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/1/comments",
  "events_url": "https://api.github.com/repos/relentlessbreakfast/test/issues/1/events",
  "html_url": "https://github.com/relentlessbreakfast/test/issues/1",
  "id": 81161192,
  "number": 1,
  "title": "learn mysql",
  "user": {
  "login": "kuychaco",
  "id": 7910250,
  "avatar_url": "https://avatars.githubusercontent.com/u/7910250?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kuychaco",
  "html_url": "https://github.com/kuychaco",
  "followers_url": "https://api.github.com/users/kuychaco/followers",
  "following_url": "https://api.github.com/users/kuychaco/following{/other_user}",
  "gists_url": "https://api.github.com/users/kuychaco/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kuychaco/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kuychaco/subscriptions",
  "organizations_url": "https://api.github.com/users/kuychaco/orgs",
  "repos_url": "https://api.github.com/users/kuychaco/repos",
  "events_url": "https://api.github.com/users/kuychaco/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kuychaco/received_events",
  "type": "User",
  "site_admin": false
  },
  "labels": [ ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": {
  "url": "https://api.github.com/repos/relentlessbreakfast/test/milestones/1",
  "html_url": "https://github.com/relentlessbreakfast/test/milestones/set%20up%20database",
  "labels_url": "https://api.github.com/repos/relentlessbreakfast/test/milestones/1/labels",
  "id": 1134851,
  "number": 1,
  "title": "set up database",
  "description": "",
  "creator": {
  "login": "kuychaco",
  "id": 7910250,
  "avatar_url": "https://avatars.githubusercontent.com/u/7910250?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kuychaco",
  "html_url": "https://github.com/kuychaco",
  "followers_url": "https://api.github.com/users/kuychaco/followers",
  "following_url": "https://api.github.com/users/kuychaco/following{/other_user}",
  "gists_url": "https://api.github.com/users/kuychaco/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kuychaco/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kuychaco/subscriptions",
  "organizations_url": "https://api.github.com/users/kuychaco/orgs",
  "repos_url": "https://api.github.com/users/kuychaco/repos",
  "events_url": "https://api.github.com/users/kuychaco/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kuychaco/received_events",
  "type": "User",
  "site_admin": false
  },
  "open_issues": 2,
  "closed_issues": 0,
  "state": "open",
  "created_at": "2015-05-26T22:15:38Z",
  "updated_at": "2015-05-26T22:17:25Z",
  "due_on": null,
  "closed_at": null
  },
  "comments": 0,
  "created_at": "2015-05-26T22:16:01Z",
  "updated_at": "2015-05-26T22:16:01Z",
  "closed_at": null,
  "body": ""
  }
];